import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { parseSchemaFromDbArgs, runCliAsync, runSchemaFromDb } from '../cli.js';

/**
 * Build a tiny `Connector` shim that satisfies the `isConnector` ducktype
 * check + provides a `reflectSchema` that returns a fixed table list. We
 * write it to a temp file so we can exercise the dynamic-import path the
 * CLI uses.
 */
function writeFakeConnectorModule(dir: string, withReflect: boolean): string {
  const path = join(dir, 'fake-connector.mjs');
  const reflectImpl = withReflect
    ? `async reflectSchema() {
         return [
           {
             name: 'widgets',
             columns: [
               { name: 'id', type: 'integer', primary: true, autoIncrement: true, nullable: false, unique: false },
               { name: 'sku', type: 'string', primary: false, autoIncrement: false, nullable: false, unique: true, limit: 64 },
               { name: 'archivedAt', type: 'timestamp', primary: false, autoIncrement: false, nullable: true, unique: false },
             ],
             indexes: [{ columns: ['sku'], unique: true, name: 'idx_widgets_sku' }],
             primaryKey: 'id',
           },
         ];
       }`
    : '';
  const source = `
const fakeConnector = {
  query: async () => [],
  count: async () => 0,
  select: async () => [],
  updateAll: async () => [],
  deleteAll: async () => [],
  batchInsert: async () => [],
  execute: async () => [],
  transaction: async (fn) => fn(),
  aggregate: async () => undefined,
  hasTable: async () => false,
  createTable: async () => {},
  dropTable: async () => {},
  alterTable: async () => {},
  upsert: async () => [],
  deltaUpdate: async () => 0,
  ${reflectImpl}
};
export default fakeConnector;
`;
  writeFileSync(path, source, 'utf8');
  return path;
}

describe('parseSchemaFromDbArgs', () => {
  it('parses --connector / --output / --import-path', () => {
    const { options } = parseSchemaFromDbArgs([
      '--connector',
      './db.js',
      '--output',
      './schema.ts',
      '--import-path',
      '@my/core',
    ]);
    expect(options.connector).toBe('./db.js');
    expect(options.output).toBe('./schema.ts');
    expect(options.importPath).toBe('@my/core');
  });

  it('rejects unknown flags', () => {
    expect(() => parseSchemaFromDbArgs(['--bogus'])).toThrow(/Unknown flag/);
  });

  it('rejects unexpected positional args', () => {
    expect(() => parseSchemaFromDbArgs(['hello', '--connector', 'x'])).toThrow(/Unexpected/);
  });
});

describe('runSchemaFromDb', () => {
  it('writes a typed-schema TS file from the connector reflection', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'nm-schema-from-db-'));
    const connectorPath = writeFakeConnectorModule(dir, true);
    const out = join(dir, 'schema.ts');
    const result = await runSchemaFromDb({ connector: connectorPath, output: out });
    expect(result.path).toBe(out);
    expect(result.tables).toHaveLength(1);

    const contents = readFileSync(out, 'utf8');
    expect(contents).toContain('// Generated by @next-model/migrations');
    expect(contents).toContain('export const schema = defineSchema({');
    expect(contents).toContain('widgets: {');
    expect(contents).toContain('id: { type: "integer", primary: true, autoIncrement: true');
    expect(contents).toContain('sku: { type: "string", unique: true, limit: 64 }');
    expect(contents).toContain('archivedAt: { type: "timestamp", null: true }');
    expect(contents).toContain('idx_widgets_sku');
  });

  it('throws if the connector does not implement reflectSchema', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'nm-schema-from-db-noref-'));
    const connectorPath = writeFakeConnectorModule(dir, false);
    const out = join(dir, 'schema.ts');
    await expect(runSchemaFromDb({ connector: connectorPath, output: out })).rejects.toThrow(
      /reflectSchema/,
    );
  });

  it('honours --import-path for the emitted defineSchema import', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'nm-schema-from-db-importpath-'));
    const connectorPath = writeFakeConnectorModule(dir, true);
    const out = join(dir, 'schema.ts');
    await runSchemaFromDb({
      connector: connectorPath,
      output: out,
      importPath: '@my/core-alias',
    });
    const contents = readFileSync(out, 'utf8');
    expect(contents).toContain("from '@my/core-alias'");
  });
});

describe('runCliAsync — schema-from-db subcommand', () => {
  it('runs end-to-end and writes the schema file', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'nm-schema-from-db-cli-'));
    const connectorPath = writeFakeConnectorModule(dir, true);
    const out = join(dir, 'schema.ts');
    const stdoutChunks: string[] = [];
    const result = await runCliAsync({
      args: ['schema-from-db', '--connector', connectorPath, '--output', out],
      stdout: {
        write: (c: string) => {
          stdoutChunks.push(c);
          return true;
        },
      } as NodeJS.WritableStream,
      stderr: { write: () => true } as NodeJS.WritableStream,
    });
    expect(result.exitCode).toBe(0);
    expect(result.path).toBe(out);
    expect(stdoutChunks.join('')).toContain('wrote');
    expect(readFileSync(out, 'utf8')).toContain('widgets: {');
  });

  it('exits 2 with usage when --connector or --output is missing', async () => {
    const stderrChunks: string[] = [];
    const result = await runCliAsync({
      args: ['schema-from-db', '--connector', './x.js'],
      stdout: { write: () => true } as NodeJS.WritableStream,
      stderr: {
        write: (c: string) => {
          stderrChunks.push(c);
          return true;
        },
      } as NodeJS.WritableStream,
    });
    expect(result.exitCode).toBe(2);
    expect(stderrChunks.join('')).toContain('--connector and --output');
  });

  it('exits 1 and reports if reflectSchema is missing', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'nm-schema-from-db-cli-noref-'));
    const connectorPath = writeFakeConnectorModule(dir, false);
    const out = join(dir, 'schema.ts');
    const stderrChunks: string[] = [];
    const result = await runCliAsync({
      args: ['schema-from-db', '--connector', connectorPath, '--output', out],
      stdout: { write: () => true } as NodeJS.WritableStream,
      stderr: {
        write: (c: string) => {
          stderrChunks.push(c);
          return true;
        },
      } as NodeJS.WritableStream,
    });
    expect(result.exitCode).toBe(1);
    expect(stderrChunks.join('')).toContain('reflectSchema');
  });

  it('falls through to the migration generator for non-subcommand invocations', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'nm-schema-from-db-fallthrough-'));
    const stdoutChunks: string[] = [];
    const result = await runCliAsync({
      args: ['create users', '--dir', dir, '--create-table', 'users'],
      now: new Date(Date.UTC(2026, 0, 2, 3, 4, 5, 6)),
      stdout: {
        write: (c: string) => {
          stdoutChunks.push(c);
          return true;
        },
      } as NodeJS.WritableStream,
      stderr: { write: () => true } as NodeJS.WritableStream,
    });
    expect(result.exitCode).toBe(0);
    expect(stdoutChunks.join('')).toContain('20260102030405006_create_users.ts');
  });
});
