packages:
  - "packages/core"
  - "packages/knex-connector"
  - "packages/postgres-connector"
  - "packages/sqlite-connector"
  - "packages/data-api-connector"
  - "packages/local-storage-connector"
  - "packages/migrations"
