packages:
  - "packages/core"
  - "packages/knex-connector"
  - "packages/postgres-connector"
  - "packages/sqlite-connector"
  - "packages/mysql-connector"
  - "packages/mariadb-connector"
  - "packages/redis-connector"
  - "packages/valkey-connector"
  - "packages/mongodb-connector"
  - "packages/aurora-data-api-connector"
  - "packages/local-storage-connector"
  - "packages/migrations"
  - "packages/express-rest-api"
  - "packages/graphql-api"
  - "packages/nextjs-api"
  - "packages/migrations-generator"
  - "packages/zod"
  - "packages/typebox"
  - "packages/arktype"
  - "demos/node/server/*"
  - "demos/node/client/*"
  - "demos/react/*"
  - "demos/nextjs/*"
