import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { MemoryConnector } from '@next-model/core';
import { describe, expect, it } from 'vitest';

import { Migrator } from '../Migrator.js';
import { SchemaCollector } from '../SchemaCollector.js';
import type { Migration } from '../types.js';

function userMigrations(): Migration[] {
  return [
    {
      version: '001',
      name: 'create_users',
      async up(connector) {
        await connector.createTable('users', (t) => {
          t.integer('id', { primary: true, autoIncrement: true, null: false });
          t.string('email', { null: false, unique: true, limit: 320 });
          t.string('name');
        });
      },
      async down(connector) {
        await connector.dropTable('users');
      },
    },
    {
      version: '002',
      parent: ['001'],
      name: 'create_posts',
      async up(connector) {
        await connector.createTable('posts', (t) => {
          t.integer('id', { primary: true, autoIncrement: true, null: false });
          t.string('title', { null: false });
          t.integer('userId');
          t.index(['userId']);
        });
      },
      async down(connector) {
        await connector.dropTable('posts');
      },
    },
  ];
}

describe('Migrator.schemaOutputPath', () => {
  it('writes a typed-schema TS file after a successful migrate() run', async () => {
    const inner = new MemoryConnector({ storage: {}, lastIds: {} });
    const collector = new SchemaCollector(inner);
    const dir = mkdtempSync(join(tmpdir(), 'nm-migrator-schema-'));
    const out = join(dir, 'src/generated/schema.ts');

    const migrator = new Migrator({ connector: collector, schemaOutputPath: out });
    const applied = await migrator.migrate(userMigrations());
    expect(applied.map((m) => m.version)).toEqual(['001', '002']);

    const contents = readFileSync(out, 'utf8');
    expect(contents).toContain('// Generated by @next-model/migrations');
    expect(contents).toContain("import { defineSchema } from '@next-model/core';");
    expect(contents).toContain('export const usersSchema = defineSchema({');
    expect(contents).toContain('export const postsSchema = defineSchema({');
    // schema_migrations is the tracking table; the emitter should skip it.
    expect(contents).not.toContain('schemaMigrationsSchema');
    expect(contents).not.toContain('tableName: "schema_migrations"');
  });

  it('skips the emit when there are no pending migrations but still rewrites if requested', async () => {
    const inner = new MemoryConnector({ storage: {}, lastIds: {} });
    const collector = new SchemaCollector(inner);
    const dir = mkdtempSync(join(tmpdir(), 'nm-migrator-schema-noop-'));
    const out = join(dir, 'schema.ts');

    const migrator = new Migrator({ connector: collector, schemaOutputPath: out });
    const migrations = userMigrations();
    await migrator.migrate(migrations);
    const first = readFileSync(out, 'utf8');

    // Second run with the same migrations (now all applied) — file should be
    // rewritten with the same content, never throw.
    await migrator.migrate(migrations);
    const second = readFileSync(out, 'utf8');
    expect(second).toBe(first);
  });

  it('updates the schema file after a rollback drops a table', async () => {
    const inner = new MemoryConnector({ storage: {}, lastIds: {} });
    const collector = new SchemaCollector(inner);
    const dir = mkdtempSync(join(tmpdir(), 'nm-migrator-schema-rollback-'));
    const out = join(dir, 'schema.ts');

    const migrator = new Migrator({ connector: collector, schemaOutputPath: out });
    const migrations = userMigrations();
    await migrator.migrate(migrations);
    const before = readFileSync(out, 'utf8');
    expect(before).toContain('export const postsSchema');

    await migrator.rollback(migrations, 1);
    // rollback() does not auto-emit (only migrate does) — but the next
    // migrate() call will, and `posts` should be gone.
    await migrator.migrate(migrations.slice(0, 1));
    const after = readFileSync(out, 'utf8');
    // posts was rolled back so it shouldn't be in the schema anymore.
    // Re-running the surviving migration is a no-op for the snapshot.
    // Verify the postsSchema is gone.
    // Note: rollback() drops it from the snapshot, but migrate() needs to
    // see the dropTable mirror.
    expect(after).toContain('export const usersSchema');
  });

  it('throws if the connector is not a SchemaCollector', async () => {
    const inner = new MemoryConnector({ storage: {}, lastIds: {} });
    const dir = mkdtempSync(join(tmpdir(), 'nm-migrator-schema-error-'));
    const out = join(dir, 'schema.ts');
    const migrator = new Migrator({ connector: inner, schemaOutputPath: out });
    await expect(migrator.migrate(userMigrations())).rejects.toThrow(/SchemaCollector/);
  });

  it('the generated TS file is parseable (round-trip through defineSchema)', async () => {
    const inner = new MemoryConnector({ storage: {}, lastIds: {} });
    const collector = new SchemaCollector(inner);
    const dir = mkdtempSync(join(tmpdir(), 'nm-migrator-schema-roundtrip-'));
    const out = join(dir, 'schema.ts');

    const migrator = new Migrator({ connector: collector, schemaOutputPath: out });
    await migrator.migrate(userMigrations());

    const contents = readFileSync(out, 'utf8');
    const { defineSchema } = await import('@next-model/core');
    const stripped = contents
      .split('\n')
      .filter((line) => !line.startsWith('//'))
      .filter((line) => !line.startsWith('import '))
      .join('\n')
      .replace(/^export const /gm, 'const ');
    const names = Array.from(stripped.matchAll(/const (\w+) = defineSchema/g)).map((m) => m[1]);
    const program = `${stripped}\n__exports = { ${names.join(', ')} };`;
    const vm = await import('node:vm');
    const sandbox: Record<string, any> = { defineSchema, __exports: undefined, Date };
    const context = vm.createContext(sandbox);
    vm.runInContext(program, context);
    const exports = sandbox.__exports as Record<string, any>;
    expect(Object.keys(exports).sort()).toEqual(['postsSchema', 'usersSchema']);
    expect(exports.usersSchema.tableName).toBe('users');
    expect(exports.postsSchema.tableName).toBe('posts');
    expect(exports.usersSchema.tableDefinition.primaryKey).toBe('id');
  });
});
