services:
  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 10
